from enum import IntEnum
from typing import overload, NewType, Optional, Tuple

from OCC.Core.Standard import *
from OCC.Core.NCollection import *
from OCC.Core.Expr import *
from OCC.Core.TCollection import *

#the following typedef cannot be wrapped as is
ExprIntrp_ListIteratorOfStackOfGeneralExpression = NewType('ExprIntrp_ListIteratorOfStackOfGeneralExpression', Any)
#the following typedef cannot be wrapped as is
ExprIntrp_ListIteratorOfStackOfGeneralFunction = NewType('ExprIntrp_ListIteratorOfStackOfGeneralFunction', Any)
#the following typedef cannot be wrapped as is
ExprIntrp_ListIteratorOfStackOfGeneralRelation = NewType('ExprIntrp_ListIteratorOfStackOfGeneralRelation', Any)
#the following typedef cannot be wrapped as is
ExprIntrp_SequenceOfNamedExpression = NewType('ExprIntrp_SequenceOfNamedExpression', Any)
#the following typedef cannot be wrapped as is
ExprIntrp_SequenceOfNamedFunction = NewType('ExprIntrp_SequenceOfNamedFunction', Any)
#the following typedef cannot be wrapped as is
ExprIntrp_StackOfGeneralExpression = NewType('ExprIntrp_StackOfGeneralExpression', Any)
#the following typedef cannot be wrapped as is
ExprIntrp_StackOfGeneralFunction = NewType('ExprIntrp_StackOfGeneralFunction', Any)
#the following typedef cannot be wrapped as is
ExprIntrp_StackOfGeneralRelation = NewType('ExprIntrp_StackOfGeneralRelation', Any)

class exprintrp:
	pass

class ExprIntrp_Analysis:
	def __init__(self) -> None: ...
	def GetFunction(self, name: TCollection_AsciiString) -> Expr_NamedFunction: ...
	def GetNamed(self, name: TCollection_AsciiString) -> Expr_NamedExpression: ...
	def IsExpStackEmpty(self) -> bool: ...
	def IsRelStackEmpty(self) -> bool: ...
	def Pop(self) -> Expr_GeneralExpression: ...
	def PopFunction(self) -> Expr_GeneralFunction: ...
	def PopName(self) -> TCollection_AsciiString: ...
	def PopRelation(self) -> Expr_GeneralRelation: ...
	def PopValue(self) -> int: ...
	def Push(self, exp: Expr_GeneralExpression) -> None: ...
	def PushFunction(self, func: Expr_GeneralFunction) -> None: ...
	def PushName(self, name: TCollection_AsciiString) -> None: ...
	def PushRelation(self, rel: Expr_GeneralRelation) -> None: ...
	def PushValue(self, degree: int) -> None: ...
	def ResetAll(self) -> None: ...
	def SetMaster(self, agen: ExprIntrp_Generator) -> None: ...
	@overload
	def Use(self, func: Expr_NamedFunction) -> None: ...
	@overload
	def Use(self, named: Expr_NamedExpression) -> None: ...

class ExprIntrp_Generator(Standard_Transient):
	def GetFunction(self, name: TCollection_AsciiString) -> Expr_NamedFunction: ...
	def GetFunctions(self) -> ExprIntrp_SequenceOfNamedFunction: ...
	@overload
	def GetNamed(self) -> ExprIntrp_SequenceOfNamedExpression: ...
	@overload
	def GetNamed(self, name: TCollection_AsciiString) -> Expr_NamedExpression: ...
	@overload
	def Use(self, func: Expr_NamedFunction) -> None: ...
	@overload
	def Use(self, named: Expr_NamedExpression) -> None: ...

class ExprIntrp_GenExp(ExprIntrp_Generator):
	@staticmethod
	def Create() -> ExprIntrp_GenExp: ...
	def Expression(self) -> Expr_GeneralExpression: ...
	def IsDone(self) -> bool: ...
	def Process(self, str: TCollection_AsciiString) -> None: ...

class ExprIntrp_GenFct(ExprIntrp_Generator):
	@staticmethod
	def Create() -> ExprIntrp_GenFct: ...
	def IsDone(self) -> bool: ...
	def Process(self, str: TCollection_AsciiString) -> None: ...

class ExprIntrp_GenRel(ExprIntrp_Generator):
	@staticmethod
	def Create() -> ExprIntrp_GenRel: ...
	def IsDone(self) -> bool: ...
	def Process(self, str: TCollection_AsciiString) -> None: ...
	def Relation(self) -> Expr_GeneralRelation: ...

# harray1 classes
# harray2 classes
# hsequence classes

ExprIntrp_GenExp_Create = ExprIntrp_GenExp.Create
ExprIntrp_GenFct_Create = ExprIntrp_GenFct.Create
ExprIntrp_GenRel_Create = ExprIntrp_GenRel.Create
